import { Routes, Route, useNavigate, useLocation } from "react-router-dom";
import { useEffect } from "react";
import Nav              from "./components/Nav";
import Footer           from "./components/Footer";
import HomePage         from "./pages/HomePage";
import AboutPage        from "./pages/AboutPage";
import ExpertisePage    from "./pages/ExpertisePage";
import MediaPage        from "./pages/MediaPage";
import PhilanthropyPage from "./pages/PhilanthropyPage";
import InsightsPage     from "./pages/InsightsPage";
import ContactPage      from "./pages/ContactPage";
import InsightArticlePage from "./pages/InsightArticlePage";
import LupusSummit      from "./pages/articles/LupusSummit";


function ScrollToTop() {
  const { pathname } = useLocation();
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [pathname]);
  return null;
}

export default function App() {
  const navigate = useNavigate();
  const location = useLocation();

  const currentPage = location.pathname.replace("/", "") || "home";
  const isArticlePage = location.pathname.startsWith("/insights/") || location.pathname.startsWith("/philanthropy/");

  const navigateTo = (p) => {
    const path = p === "home" ? "/" : p.startsWith("/") ? p : `/${p}`;
    navigate(path);
  };

  return (
    <>
    <ScrollToTop />
      <Nav
        currentPage={currentPage}
        navigate={navigateTo}
        transparent={isArticlePage}
        forceDark={
          !isArticlePage && (
            currentPage === "about" ||
            currentPage === "expertise" ||
            currentPage === "media" ||
            currentPage === "contact" ||
            currentPage === "philanthropy" ||
            currentPage === "insights"
          )
        }
      />
      <main>
        <Routes>
          <Route path="/"              element={<HomePage navigate={navigateTo} />} />
          <Route path="/about"         element={<AboutPage />} />
          <Route path="/expertise"     element={<ExpertisePage />} />
          <Route path="/media"         element={<MediaPage navigate={navigateTo} />} />
          <Route path="/philanthropy"  element={<PhilanthropyPage />} />
          <Route path="/insights"      element={<InsightsPage />} />
          <Route path="/contact"       element={<ContactPage />} />

          {/*
            Insights articles are served from a single dynamic route. Content
            lives in content/insights/*.md and the registry is generated by
            scripts/build-insights.mjs.
          */}
          <Route path="/insights/:slug" element={<InsightArticlePage />} />

          {/* Non-insight article kept as-is */}
          <Route path="/philanthropy/lupus-summit" element={<LupusSummit />} />
        </Routes>
      </main>
      <Footer navigate={navigateTo} />
    </>
  );
}
